project:
  type: website

website:
  title: "Fonctions et programmation fonctionnelle"
  sidebar:
    style: "floating"
    contents:
      - href: index.qmd
        text: Introduction
      - href: fonctions.qmd
        text: Rappel sur les fonctions en R
      - href: fonctions_ordre_superieur_1.qmd
        text: Fonctions d'ordre supérieur 1 (arguments)
      - href: fonctions_ordre_superieur_2.qmd
        text: Fonctions d'ordre supérieur 2 (retours)
      - href: evaluation.qmd
        text: Évaluation des fonctions en R
      - href: poo_s3.qmd
        text: Programmation fonctionnelle objet en R (S3)
    search: false

format:
  html:
    toc: true

filters:
  - webr
  - naquiz

webr: 
  show-startup-message: false
